GET http://localhost:8080/devops_starter_war_exploded/api/xxx

###
PUT http://localhost:8080/api/persons/edit
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"id": 2, "email": "test@test.dk"}